#!/usr/bin/env node
// Regenerate .triage/<kind>/index.md from the YAML frontmatter of every results.md.
// Usage: node .claude/skills/triage/scripts/reindex.mjs [issues|prs]
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const kind = process.argv[2] ?? "prs";
if (kind !== "issues" && kind !== "prs") {
  console.error("usage: reindex.mjs [issues|prs]");
  process.exit(1);
}

const root = execFileSync("git", ["worktree", "list"], { encoding: "utf8" }).split("\n")[0].split(" ")[0];
const dir = join(root, ".triage", kind);
if (!existsSync(dir)) {
  console.error(`no such directory: ${dir}`);
  process.exit(1);
}

// Minimal frontmatter reader: flat `key: value` pairs only, which is all the format uses.
function frontmatter(file) {
  const text = readFileSync(file, "utf8");
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const out = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (kv) out[kv[1]] = kv[2].trim().replace(/^["'](.*)["']$/, "$1");
  }
  return out;
}

const rows = [];
for (const entry of readdirSync(dir, { withFileTypes: true })) {
  if (!entry.isDirectory() || !/^\d+$/.test(entry.name)) continue;
  const file = join(dir, entry.name, "results.md");
  if (!existsSync(file)) continue;
  const fm = frontmatter(file);
  rows.push({
    number: Number(entry.name),
    status: fm?.status ?? "unknown",
    verdict: fm?.verdict ?? "—",
    title: fm?.title ?? "",
    author: fm?.author ?? "",
  });
}
rows.sort((a, b) => b.number - a.number);

const noun = kind === "prs" ? "pull" : "issues";
const counts = {};
for (const r of rows) counts[r.verdict] = (counts[r.verdict] ?? 0) + 1;
const done = rows.filter((r) => r.status === "done").length;

const lines = [
  `# ${kind === "prs" ? "Open PR" : "Open issue"} triage index`,
  "",
  `Generated by \`.claude/skills/triage/scripts/reindex.mjs\` — do not hand-edit. Derived from the frontmatter of \`.triage/${kind}/*/results.md\`.`,
  "",
  `${rows.length} written up, ${done} marked \`done\`.`,
  "",
  "## Verdicts",
  "",
  ...Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .map(([v, n]) => `- \`${v}\` — ${n}`),
  "",
  "## Entries",
  "",
  "| # | Verdict | Status | Title | Author | Write-up |",
  "| --- | --- | --- | --- | --- | --- |",
  ...rows.map((r) =>
    [
      `[#${r.number}](https://github.com/colinhacks/zod/${noun}/${r.number})`,
      `\`${r.verdict}\``,
      r.status,
      r.title.replace(/\|/g, "\\|"),
      r.author ? `@${r.author}` : "",
      `[results.md](${r.number}/results.md)`,
    ].join(" | ").replace(/^/, "| ").concat(" |")
  ),
  "",
];

writeFileSync(join(dir, "index.md"), lines.join("\n"));
console.log(`wrote ${join(dir, "index.md")} (${rows.length} entries)`);
