import { z } from "zod";
const Type1 = z.object({});
let test1;
const Type2 = Type1.extend({});
let test2;
const Type3 = Type2.extend({});
let test3;
const Type4 = Type3.extend({});
let test4;
const Type5 = Type4.extend({});
let test5;
const Type6 = Type5.extend({});
let test6;
const Type7 = Type6.extend({});
let test7;
const Type8 = Type7.extend({});
let test8;
const Type9 = Type8.extend({});
let test9;
const Type10 = Type9.extend({});
let test10;
const Type11 = Type10.extend({});
let test11;
const Type12 = Type11.extend({});
let test12;
const Type13 = Type12.extend({});
let test13;
const Type14 = Type13.extend({});
let test14;
const Type15 = Type14.extend({});
let test15;
