"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const z1 = require("zod");
const zod_1 = require("zod");
const zod_2 = require("zod");
const z4 = require("zod/v4");
const z5 = require("zod/v3");
const z6 = require("zod/v4/mini");
const z7 = require("zod/v4-mini");
const fr_js_1 = require("zod/v4/locales/fr.js");
console.log(z1.string().parse("Hello, world!"));
;
console.log(zod_1.default.string().parse("Hello, world!"));
;
console.log(zod_2.z.string().parse("Hello, world!"));
;
console.log(z4.string().parse("Hello, world!"));
;
console.log(z5.string().parse("Hello, world!"));
;
console.log(z6.string().parse("Hello, world!"));
;
console.log(z7.string().parse("Hello, world!"));
;
z4.config((0, fr_js_1.default)());
