import * as z from "zod";
export declare const dengsxxhwefcoscsx: z.ZodInterface<{
    nxlpltjb: z.ZodString;
    imiusvop: z.ZodString;
    ijyrysqv: z.ZodString;
    pdwexobi: z.ZodString;
    dhdupqku: z.ZodString;
    icvkioth: z.ZodString;
    uxddjooi: z.ZodString;
    hqahubkj: z.ZodString;
    xieqprzy: z.ZodString;
    yzyrxhou: z.ZodString;
}, Record<never, unknown>>;
export declare const pdgmzrvwgaupljdcs: z.ZodInterface<{
    nrbxeefl: z.ZodString;
    rndreeil: z.ZodString;
    zhknfbul: z.ZodString;
    lkypfuhr: z.ZodString;
    gzgsbxgv: z.ZodString;
    uorzlkhg: z.ZodString;
    vzecxfxb: z.ZodString;
    vxlksukq: z.ZodString;
    iwgmngoo: z.ZodString;
    lkurvevu: z.ZodString;
}, Record<never, unknown>>;
export declare const lnzwjttdttdmyimer: z.ZodInterface<{
    mevchlcj: z.ZodString;
    cmxdmemd: z.ZodString;
    nsmageof: z.ZodString;
    rzflagvs: z.ZodString;
    byosomzs: z.ZodString;
    rfiucbxj: z.ZodString;
    yiviedgj: z.ZodString;
    bcmrihvl: z.ZodString;
    jczpfuqf: z.ZodString;
    srziinjm: z.ZodString;
}, Record<never, unknown>>;
export declare const wxwhxpbtaitiommoy: z.ZodInterface<{
    jarmhull: z.ZodString;
    fraqflku: z.ZodString;
    tbvmmxyb: z.ZodString;
    aesyqqfr: z.ZodString;
    ujjdhlku: z.ZodString;
    zujxixjk: z.ZodString;
    paliyqxo: z.ZodString;
    niguecjb: z.ZodString;
    kfnukebj: z.ZodString;
    djhbdtvh: z.ZodString;
}, Record<never, unknown>>;
export declare const xdfpjmbuxjzpdkbez: z.ZodInterface<{
    jarrzcay: z.ZodString;
    bdqgygvv: z.ZodString;
    bjbbetnq: z.ZodString;
    ymvxyvww: z.ZodString;
    pntjptvq: z.ZodString;
    lekivwbq: z.ZodString;
    majsfiuw: z.ZodString;
    ezzrhhes: z.ZodString;
    vjkgiwvb: z.ZodString;
    eqfermva: z.ZodString;
}, Record<never, unknown>>;
export declare const kxiakrcuiodhbcpgf: z.ZodInterface<{
    ocejwryk: z.ZodString;
    bgmamipq: z.ZodString;
    khaldxrc: z.ZodString;
    oivwazbc: z.ZodString;
    weffwtbv: z.ZodString;
    yecnegsy: z.ZodString;
    mfmjdixm: z.ZodString;
    cslwbfdh: z.ZodString;
    wdfnqrrg: z.ZodString;
    utrhpuzr: z.ZodString;
}, Record<never, unknown>>;
export declare const uqlfaejmgkeapeesz: z.ZodInterface<{
    gmgoffjz: z.ZodString;
    asyqocqy: z.ZodString;
    cvgvbiww: z.ZodString;
    mwwyjnnj: z.ZodString;
    cnznydnu: z.ZodString;
    nkhuikip: z.ZodString;
    izmeuigk: z.ZodString;
    ifbqahke: z.ZodString;
    zubmcccb: z.ZodString;
    oxrbxowl: z.ZodString;
}, Record<never, unknown>>;
export declare const fehrmywiqmkhvnlik: z.ZodInterface<{
    tukawryc: z.ZodString;
    jptcoqet: z.ZodString;
    srkeetbx: z.ZodString;
    rukqqktw: z.ZodString;
    kytkmgob: z.ZodString;
    hpxtzvqk: z.ZodString;
    nfrxawvk: z.ZodString;
    hjupdckq: z.ZodString;
    nmzpdvna: z.ZodString;
    sihclgil: z.ZodString;
}, Record<never, unknown>>;
export declare const byusrrbowfejbdqxs: z.ZodInterface<{
    bucjbxti: z.ZodString;
    qwgiwmbd: z.ZodString;
    beodcmeq: z.ZodString;
    pwdindme: z.ZodString;
    ybexbeme: z.ZodString;
    ueqeitld: z.ZodString;
    iodhflnm: z.ZodString;
    wialpbwo: z.ZodString;
    rqsoeknc: z.ZodString;
    injbeyoe: z.ZodString;
}, Record<never, unknown>>;
export declare const jbrespqokqjbdvete: z.ZodInterface<{
    jkmymkok: z.ZodString;
    bdrqnfpc: z.ZodString;
    ckhihyic: z.ZodString;
    xatkvdzs: z.ZodString;
    loajhbxi: z.ZodString;
    gkfrrtug: z.ZodString;
    pcdgmkmy: z.ZodString;
    zsrekcoc: z.ZodString;
    gdjthjql: z.ZodString;
    eqoajdaz: z.ZodString;
}, Record<never, unknown>>;
export declare const wvkntijtquozljarg: z.ZodInterface<{
    wfrgodiy: z.ZodString;
    oeyjsfss: z.ZodString;
    kwitiofo: z.ZodString;
    aprzafko: z.ZodString;
    qsmutsbc: z.ZodString;
    onltzcbl: z.ZodString;
    omailnqe: z.ZodString;
    sebyycia: z.ZodString;
    tmyxaexq: z.ZodString;
    rbcyklpg: z.ZodString;
}, Record<never, unknown>>;
export declare const vwtjklcopwatkmmyc: z.ZodInterface<{
    mzweszbf: z.ZodString;
    lztfvjcc: z.ZodString;
    wxndluja: z.ZodString;
    ymwhvdzm: z.ZodString;
    ndeidqmd: z.ZodString;
    cihaaxti: z.ZodString;
    ussesmye: z.ZodString;
    nujqbdoh: z.ZodString;
    fapzvncy: z.ZodString;
    wcifelaj: z.ZodString;
}, Record<never, unknown>>;
export declare const txxjoeazlyhxtwglm: z.ZodInterface<{
    qwyjvrhz: z.ZodString;
    ljqbntwj: z.ZodString;
    nownqdic: z.ZodString;
    hmbsacrp: z.ZodString;
    nimucwvj: z.ZodString;
    zvtvrdlo: z.ZodString;
    spvpxbtf: z.ZodString;
    pizchmux: z.ZodString;
    tcealcgv: z.ZodString;
    smveltzk: z.ZodString;
}, Record<never, unknown>>;
export declare const oaqohricqfyydxhoi: z.ZodInterface<{
    znxypqju: z.ZodString;
    totybdzd: z.ZodString;
    mtuvfjnu: z.ZodString;
    tvopoxbc: z.ZodString;
    nnoxjbwx: z.ZodString;
    dseftqcd: z.ZodString;
    ptzidhmg: z.ZodString;
    dkduscru: z.ZodString;
    jbkfackz: z.ZodString;
    ysskolfh: z.ZodString;
}, Record<never, unknown>>;
export declare const moykbqwxoifhvtjcx: z.ZodInterface<{
    bhgeyqpx: z.ZodString;
    kfyzuasr: z.ZodString;
    xzmzpnvt: z.ZodString;
    whfoamgr: z.ZodString;
    bmyymbih: z.ZodString;
    zkvwharw: z.ZodString;
    mfnrtqot: z.ZodString;
    vhppxewx: z.ZodString;
    yktxfuum: z.ZodString;
    lvqsauei: z.ZodString;
}, Record<never, unknown>>;
export declare const msxbkghqhosjezawq: z.ZodInterface<{
    ktjlkwpx: z.ZodString;
    qwbidotu: z.ZodString;
    hccnsbmv: z.ZodString;
    sjsltzkt: z.ZodString;
    szogonol: z.ZodString;
    agwllquw: z.ZodString;
    wbhxnppx: z.ZodString;
    srguvkts: z.ZodString;
    gaswddyy: z.ZodString;
    gjijopeb: z.ZodString;
}, Record<never, unknown>>;
export declare const vtrqxmxlukpcfpvlu: z.ZodInterface<{
    ximbawkl: z.ZodString;
    gnpsgqjf: z.ZodString;
    xmsecjdo: z.ZodString;
    htlvcyoz: z.ZodString;
    ydzoaxvm: z.ZodString;
    ffuvvsdq: z.ZodString;
    rwndrida: z.ZodString;
    xbgalckv: z.ZodString;
    wlvtizpj: z.ZodString;
    rbezceox: z.ZodString;
}, Record<never, unknown>>;
export declare const azlahojhevoikqltp: z.ZodInterface<{
    orygydav: z.ZodString;
    ovdnscyn: z.ZodString;
    qjzqbxjw: z.ZodString;
    swqetpgo: z.ZodString;
    mjojjuxh: z.ZodString;
    ytxjyaxh: z.ZodString;
    muzmjigs: z.ZodString;
    jdbouyic: z.ZodString;
    dojisoqo: z.ZodString;
    eanqtyvp: z.ZodString;
}, Record<never, unknown>>;
export declare const wouiwqzgvjvrnneqy: z.ZodInterface<{
    yyojffza: z.ZodString;
    wtyckdmp: z.ZodString;
    xrtwlnyv: z.ZodString;
    draoybju: z.ZodString;
    wbzgczmh: z.ZodString;
    aailckin: z.ZodString;
    pfdonefy: z.ZodString;
    kvqqrecp: z.ZodString;
    vqfxtdqd: z.ZodString;
    zojhrajb: z.ZodString;
}, Record<never, unknown>>;
export declare const fpmwtuhfennbuvgpt: z.ZodInterface<{
    miettnph: z.ZodString;
    pkpbejfn: z.ZodString;
    umchmala: z.ZodString;
    mmuwwiul: z.ZodString;
    vijbwbzj: z.ZodString;
    ooskvosr: z.ZodString;
    ilcagxay: z.ZodString;
    eshjzzjp: z.ZodString;
    avsuhcgx: z.ZodString;
    rdfnihqy: z.ZodString;
}, Record<never, unknown>>;
export declare const yusxekyussfcyebzz: z.ZodInterface<{
    jipiqwub: z.ZodString;
    rkisfirv: z.ZodString;
    lgkpozin: z.ZodString;
    fiedsjys: z.ZodString;
    ipjpvahh: z.ZodString;
    hpitdkth: z.ZodString;
    viyonteu: z.ZodString;
    cxjbmtut: z.ZodString;
    barvfhmu: z.ZodString;
    kgwnzsfa: z.ZodString;
}, Record<never, unknown>>;
export declare const iaxbgbwhyilltkrnw: z.ZodInterface<{
    lbrmamwv: z.ZodString;
    dzzwdoar: z.ZodString;
    itjwhuge: z.ZodString;
    wmdguzqt: z.ZodString;
    jmgykrot: z.ZodString;
    iqynties: z.ZodString;
    ypiiiopq: z.ZodString;
    iurmlxib: z.ZodString;
    kcehhcyr: z.ZodString;
    wcckobit: z.ZodString;
}, Record<never, unknown>>;
export declare const thwnejpdquqhsdois: z.ZodInterface<{
    xkkaznma: z.ZodString;
    qrhcqfoo: z.ZodString;
    yepeacen: z.ZodString;
    wajuqkpc: z.ZodString;
    uxmplhoe: z.ZodString;
    rgvhztxk: z.ZodString;
    sieuqocb: z.ZodString;
    vyjgjqtp: z.ZodString;
    hnvnarhn: z.ZodString;
    ehonpumx: z.ZodString;
}, Record<never, unknown>>;
export declare const rglhnmlvhvsehxtyb: z.ZodInterface<{
    mgvzrpbb: z.ZodString;
    coupuaov: z.ZodString;
    xdktzejv: z.ZodString;
    hdjflhcf: z.ZodString;
    mbpfcalq: z.ZodString;
    wtwcrsja: z.ZodString;
    fzfenjcc: z.ZodString;
    ohydjtov: z.ZodString;
    sbantqug: z.ZodString;
    rtfeurge: z.ZodString;
}, Record<never, unknown>>;
export declare const maehvbeneoheyqjwz: z.ZodInterface<{
    ilaiszqh: z.ZodString;
    pdexdbgl: z.ZodString;
    vpszrfmh: z.ZodString;
    yuehqoef: z.ZodString;
    uaihmhnu: z.ZodString;
    pmmbcsum: z.ZodString;
    bgrnwqcg: z.ZodString;
    xqhspsyg: z.ZodString;
    qyergvyr: z.ZodString;
    gkezfjnb: z.ZodString;
}, Record<never, unknown>>;
export declare const oghujhwqhcjnyzsat: z.ZodInterface<{
    oxrqqjzv: z.ZodString;
    ompmmrcw: z.ZodString;
    pnpmcxiv: z.ZodString;
    vcoixudq: z.ZodString;
    lmrjjzlt: z.ZodString;
    ekelrbus: z.ZodString;
    hrdwbqzh: z.ZodString;
    cxkmeiiw: z.ZodString;
    anqqazyj: z.ZodString;
    bufleqcn: z.ZodString;
}, Record<never, unknown>>;
export declare const blxuubsylbifsfcdk: z.ZodInterface<{
    tdwsavhe: z.ZodString;
    ishpwfou: z.ZodString;
    zhkvqjyb: z.ZodString;
    nchnilsz: z.ZodString;
    dcfljabv: z.ZodString;
    qelzquoz: z.ZodString;
    aznbpnsf: z.ZodString;
    ekwxebnw: z.ZodString;
    btwqcuuy: z.ZodString;
    gaivutwk: z.ZodString;
}, Record<never, unknown>>;
export declare const fvfixrlhgsaswmalc: z.ZodInterface<{
    poypemjf: z.ZodString;
    wpbxpduw: z.ZodString;
    hitawvty: z.ZodString;
    gldoboiy: z.ZodString;
    cayqeisk: z.ZodString;
    zbjmsfhs: z.ZodString;
    hryancwd: z.ZodString;
    wwfvrkcz: z.ZodString;
    spwcjxfl: z.ZodString;
    qjhylnda: z.ZodString;
}, Record<never, unknown>>;
export declare const csqtxfxmribdipqpl: z.ZodInterface<{
    gvicunpm: z.ZodString;
    npkqyssu: z.ZodString;
    hjfxxplm: z.ZodString;
    cdhmtiwv: z.ZodString;
    xwgwpbyb: z.ZodString;
    vkdriazj: z.ZodString;
    mubhkvhp: z.ZodString;
    eqpivswu: z.ZodString;
    ffhuqtnw: z.ZodString;
    dhawcqrj: z.ZodString;
}, Record<never, unknown>>;
export declare const ektlxyktxcmbvqdfy: z.ZodInterface<{
    tsweeahk: z.ZodString;
    lamlwolx: z.ZodString;
    qxvzpawb: z.ZodString;
    mgpxnvwp: z.ZodString;
    qanivldi: z.ZodString;
    itgyhiqx: z.ZodString;
    izgwmcpl: z.ZodString;
    ylqcstla: z.ZodString;
    ntahkufp: z.ZodString;
    mqehraxo: z.ZodString;
}, Record<never, unknown>>;
export declare const tylgbfsnktznaupmh: z.ZodInterface<{
    glmqhbdz: z.ZodString;
    mzladkhz: z.ZodString;
    pjkssufp: z.ZodString;
    sbghhadv: z.ZodString;
    ghaqyvyp: z.ZodString;
    ewqkyaxn: z.ZodString;
    hbjklnft: z.ZodString;
    kicgloqb: z.ZodString;
    mddkrzfr: z.ZodString;
    gpwqrhxh: z.ZodString;
}, Record<never, unknown>>;
export declare const lojzwdnyqzupylcqz: z.ZodInterface<{
    gcijyioh: z.ZodString;
    ywyfyeqp: z.ZodString;
    qhoofguk: z.ZodString;
    qnninnuu: z.ZodString;
    imyxkapz: z.ZodString;
    psmoljoz: z.ZodString;
    ubaurueo: z.ZodString;
    agqhsjoz: z.ZodString;
    omnykuew: z.ZodString;
    bcxxvrgq: z.ZodString;
}, Record<never, unknown>>;
export declare const gsbkejeeihlhhosjz: z.ZodInterface<{
    rlnnaxuw: z.ZodString;
    acjncltu: z.ZodString;
    wycijzpk: z.ZodString;
    kkncmxoz: z.ZodString;
    fsejfhdj: z.ZodString;
    kcfyavuh: z.ZodString;
    atuzqdri: z.ZodString;
    nehtalxn: z.ZodString;
    iazkcyyc: z.ZodString;
    itvtvapf: z.ZodString;
}, Record<never, unknown>>;
export declare const jnjhankkqmdezzmvg: z.ZodInterface<{
    jmupuhnt: z.ZodString;
    nzpafjsl: z.ZodString;
    wcwaplyw: z.ZodString;
    pgtoabad: z.ZodString;
    nrjmiymn: z.ZodString;
    rpabpphb: z.ZodString;
    mxparmoz: z.ZodString;
    fqjiunyw: z.ZodString;
    cwbuycel: z.ZodString;
    dhrywwyx: z.ZodString;
}, Record<never, unknown>>;
export declare const xdbblxzbjwtjalsia: z.ZodInterface<{
    twpnbyag: z.ZodString;
    ftqsprfi: z.ZodString;
    gpndbnfo: z.ZodString;
    rwurzmvp: z.ZodString;
    psmxpckf: z.ZodString;
    rfwdymef: z.ZodString;
    lblfgwbl: z.ZodString;
    djjqemwu: z.ZodString;
    vdnctrdg: z.ZodString;
    vgxlqpup: z.ZodString;
}, Record<never, unknown>>;
export declare const oejqiuxgrgstscmjw: z.ZodInterface<{
    nusznuqk: z.ZodString;
    pqzmauow: z.ZodString;
    shbxvoru: z.ZodString;
    scyycdyi: z.ZodString;
    mwduoeit: z.ZodString;
    xdiydxbq: z.ZodString;
    sriisoye: z.ZodString;
    pucciobg: z.ZodString;
    mthoexrp: z.ZodString;
    ucqictmg: z.ZodString;
}, Record<never, unknown>>;
export declare const wgdgygygbrwqbxkqh: z.ZodInterface<{
    nbnbangu: z.ZodString;
    cayepuqp: z.ZodString;
    ttlhtcti: z.ZodString;
    bmdfhyvb: z.ZodString;
    rcjhudgo: z.ZodString;
    defjkdbl: z.ZodString;
    mufxecmh: z.ZodString;
    alygsdfl: z.ZodString;
    kwmvigdm: z.ZodString;
    qvbxilsl: z.ZodString;
}, Record<never, unknown>>;
export declare const kjokvqoqtypbcyvvs: z.ZodInterface<{
    mxhfqutq: z.ZodString;
    vntptjip: z.ZodString;
    pblstcmb: z.ZodString;
    jyhxfuxo: z.ZodString;
    rtxdnihw: z.ZodString;
    slnpiemt: z.ZodString;
    oosukkgy: z.ZodString;
    jqcopnny: z.ZodString;
    dfwizdta: z.ZodString;
    orojygqx: z.ZodString;
}, Record<never, unknown>>;
export declare const stgbzprcbbukrwtza: z.ZodInterface<{
    fnmvuuro: z.ZodString;
    gckvtosa: z.ZodString;
    wsxrwbcd: z.ZodString;
    hyaxkzjh: z.ZodString;
    jcyfvukr: z.ZodString;
    hrbnkakk: z.ZodString;
    odjsmimr: z.ZodString;
    trojwuyc: z.ZodString;
    zarauztt: z.ZodString;
    ttyqgqio: z.ZodString;
}, Record<never, unknown>>;
export declare const oogkcshykiopupjln: z.ZodInterface<{
    sqkqdlxu: z.ZodString;
    igavsqsh: z.ZodString;
    dsuqzjkm: z.ZodString;
    bgybnrcf: z.ZodString;
    pfmctjiu: z.ZodString;
    gtglapqs: z.ZodString;
    eulhgztb: z.ZodString;
    iuczffrc: z.ZodString;
    ahybpskv: z.ZodString;
    wvdtsrdn: z.ZodString;
}, Record<never, unknown>>;
export declare const yxvkfymypatubkbts: z.ZodInterface<{
    zuetoqam: z.ZodString;
    bwhmtojg: z.ZodString;
    muzmwmxl: z.ZodString;
    ilypzezj: z.ZodString;
    uqqifpse: z.ZodString;
    dwryynwk: z.ZodString;
    fgkzvctb: z.ZodString;
    ksykmvpt: z.ZodString;
    ulnmluof: z.ZodString;
    lpjhrjsz: z.ZodString;
}, Record<never, unknown>>;
export declare const eksbdrwieatcadnja: z.ZodInterface<{
    oepkqifq: z.ZodString;
    xsxhjiof: z.ZodString;
    xrqogngi: z.ZodString;
    zayxliqy: z.ZodString;
    pplfxtlb: z.ZodString;
    dvftqfgg: z.ZodString;
    jnooglmt: z.ZodString;
    qrnnfotk: z.ZodString;
    bwvrkvhz: z.ZodString;
    jorirnap: z.ZodString;
}, Record<never, unknown>>;
export declare const baiabcnquwxlfzgpr: z.ZodInterface<{
    fcqyfvbx: z.ZodString;
    rjztnycu: z.ZodString;
    yfmhndca: z.ZodString;
    laeogycl: z.ZodString;
    xzxgzpar: z.ZodString;
    vmcvmvhw: z.ZodString;
    sylrdlaj: z.ZodString;
    spxjxxlq: z.ZodString;
    llikoiez: z.ZodString;
    sacdjsvu: z.ZodString;
}, Record<never, unknown>>;
export declare const rdexdqgipwzwlcgyl: z.ZodInterface<{
    izhqesje: z.ZodString;
    cqksurky: z.ZodString;
    wagawvec: z.ZodString;
    ogwbbluv: z.ZodString;
    wkwfbvqz: z.ZodString;
    jaalaxeh: z.ZodString;
    kveyzibe: z.ZodString;
    uirtohjl: z.ZodString;
    vmluictq: z.ZodString;
    yfqlelen: z.ZodString;
}, Record<never, unknown>>;
export declare const oorwlxnrmwcvdwmoc: z.ZodInterface<{
    vsxiidxd: z.ZodString;
    gsatzofn: z.ZodString;
    gaqqkjxr: z.ZodString;
    cwzyhfmj: z.ZodString;
    cutfdbom: z.ZodString;
    zdreldvi: z.ZodString;
    pybzkswc: z.ZodString;
    slaaaqvl: z.ZodString;
    bycukams: z.ZodString;
    jpapuefx: z.ZodString;
}, Record<never, unknown>>;
export declare const zlmmakgppoolkbrdn: z.ZodInterface<{
    ieklvlpu: z.ZodString;
    bsictozr: z.ZodString;
    cugglsrp: z.ZodString;
    nofwanhn: z.ZodString;
    zgjrpcjb: z.ZodString;
    hyclqrmj: z.ZodString;
    coyiohxz: z.ZodString;
    kzjwjiwm: z.ZodString;
    heyixaez: z.ZodString;
    pkezqlkd: z.ZodString;
}, Record<never, unknown>>;
export declare const ujzxowkjwyuivlevb: z.ZodInterface<{
    btualhsm: z.ZodString;
    skwzqitd: z.ZodString;
    fayrcrcq: z.ZodString;
    sseweynz: z.ZodString;
    uvfmbqgc: z.ZodString;
    rnlklfto: z.ZodString;
    ptyykiwa: z.ZodString;
    omppfkuc: z.ZodString;
    gpenvmwe: z.ZodString;
    hywyoptr: z.ZodString;
}, Record<never, unknown>>;
export declare const gqcddccauildrzdef: z.ZodInterface<{
    ozmivssw: z.ZodString;
    xhywkwws: z.ZodString;
    tcqqjvsf: z.ZodString;
    iyyjwrjq: z.ZodString;
    rdqbjsxz: z.ZodString;
    aqghrcwe: z.ZodString;
    wofyxfwf: z.ZodString;
    vklqzgji: z.ZodString;
    khzwdixt: z.ZodString;
    ygchytpl: z.ZodString;
}, Record<never, unknown>>;
export declare const prqdjcaqbiuzymlnx: z.ZodInterface<{
    dltteklp: z.ZodString;
    jqynqvuh: z.ZodString;
    suaflicw: z.ZodString;
    ptpydmmj: z.ZodString;
    voiawtli: z.ZodString;
    drsnienv: z.ZodString;
    alceavtg: z.ZodString;
    croaszrq: z.ZodString;
    yzfjpdhv: z.ZodString;
    dxxchnke: z.ZodString;
}, Record<never, unknown>>;
export declare const wtdmswszavnrhtwuh: z.ZodInterface<{
    senammqh: z.ZodString;
    qmpptpgz: z.ZodString;
    jtuhdhfq: z.ZodString;
    utjlzuhi: z.ZodString;
    mlnrfitu: z.ZodString;
    klzhnyiz: z.ZodString;
    xpoclcxa: z.ZodString;
    jaexcbwu: z.ZodString;
    kqqdoqyi: z.ZodString;
    ccdyiobu: z.ZodString;
}, Record<never, unknown>>;
export declare const rhuuhozokcqsxxpcl: z.ZodInterface<{
    ueqnoxvo: z.ZodString;
    dtwfkgdm: z.ZodString;
    lgeiynvk: z.ZodString;
    swjwawpn: z.ZodString;
    gdpticzq: z.ZodString;
    zvbsbcum: z.ZodString;
    tbcbovio: z.ZodString;
    vbjasstc: z.ZodString;
    ehwqldtj: z.ZodString;
    tojxhlle: z.ZodString;
}, Record<never, unknown>>;
export declare const wscuozfivdnciiblx: z.ZodInterface<{
    gspnsykh: z.ZodString;
    vhytogly: z.ZodString;
    movxrynh: z.ZodString;
    pmpytvgm: z.ZodString;
    yigpfdag: z.ZodString;
    rmodvyyb: z.ZodString;
    rpetkoxi: z.ZodString;
    geagxowt: z.ZodString;
    ldabdutj: z.ZodString;
    gbhrdzoi: z.ZodString;
}, Record<never, unknown>>;
export declare const undzirjykuzgecrdx: z.ZodInterface<{
    smpdjllu: z.ZodString;
    igqowdxm: z.ZodString;
    apmxiors: z.ZodString;
    ykfoemxl: z.ZodString;
    qonoqjjk: z.ZodString;
    ocsbkcmx: z.ZodString;
    pfvasftz: z.ZodString;
    bgoiljps: z.ZodString;
    xrupdvqm: z.ZodString;
    czbqpoau: z.ZodString;
}, Record<never, unknown>>;
export declare const dzqbcexmycksuxand: z.ZodInterface<{
    jpwwzyzq: z.ZodString;
    yolmxzwa: z.ZodString;
    vlsjmdbn: z.ZodString;
    jpxebrnq: z.ZodString;
    shekpsqq: z.ZodString;
    azceprcg: z.ZodString;
    evlddjfv: z.ZodString;
    sqyvmljv: z.ZodString;
    gpguloin: z.ZodString;
    omglletn: z.ZodString;
}, Record<never, unknown>>;
export declare const epjoqvotzyojuzakm: z.ZodInterface<{
    xfspyrdz: z.ZodString;
    adrlujnl: z.ZodString;
    ozktryoh: z.ZodString;
    itziditd: z.ZodString;
    gacduvfg: z.ZodString;
    bugqagoa: z.ZodString;
    sscoovzx: z.ZodString;
    syisndvg: z.ZodString;
    ovcsgjgg: z.ZodString;
    bkoyqwpa: z.ZodString;
}, Record<never, unknown>>;
export declare const gevewdmlrtxztjzvb: z.ZodInterface<{
    mcyuhhpf: z.ZodString;
    bdvvvqnp: z.ZodString;
    fvsrrlig: z.ZodString;
    uatqocka: z.ZodString;
    xmnbxvvs: z.ZodString;
    ywdshoey: z.ZodString;
    tmvdmhkc: z.ZodString;
    lhdwgkms: z.ZodString;
    yjkiduiu: z.ZodString;
    aamczkuk: z.ZodString;
}, Record<never, unknown>>;
export declare const xpzfquwriathtxfif: z.ZodInterface<{
    tmcjjqcf: z.ZodString;
    iybjttjm: z.ZodString;
    wbaccbzc: z.ZodString;
    kckehqkh: z.ZodString;
    xmegtalp: z.ZodString;
    huxcpfry: z.ZodString;
    sfwjnscn: z.ZodString;
    xabtdwwk: z.ZodString;
    zfwcgxsm: z.ZodString;
    yuhaadwl: z.ZodString;
}, Record<never, unknown>>;
export declare const vfilotwgostaypxwh: z.ZodInterface<{
    sckmhvbi: z.ZodString;
    xtqdrdws: z.ZodString;
    ovxhepst: z.ZodString;
    paeptlpf: z.ZodString;
    bioqkmwj: z.ZodString;
    wdyuufgo: z.ZodString;
    ghypdytx: z.ZodString;
    mfczefdb: z.ZodString;
    bdotrplt: z.ZodString;
    dleryuux: z.ZodString;
}, Record<never, unknown>>;
export declare const dyzvcmqmwvkefxhzi: z.ZodInterface<{
    gmlhfokf: z.ZodString;
    wxhbsfsa: z.ZodString;
    gswqejgf: z.ZodString;
    jhywpwsl: z.ZodString;
    svekgxhy: z.ZodString;
    qmqnfxed: z.ZodString;
    lhpmelva: z.ZodString;
    piytakdo: z.ZodString;
    pldkvkkp: z.ZodString;
    xropjezn: z.ZodString;
}, Record<never, unknown>>;
export declare const apcbhoauuykloeudn: z.ZodInterface<{
    kzecgsjk: z.ZodString;
    wyqarkhl: z.ZodString;
    idxaevzk: z.ZodString;
    dzkettvm: z.ZodString;
    dpefgnjy: z.ZodString;
    glstzdrt: z.ZodString;
    kcpejusz: z.ZodString;
    wdgamhny: z.ZodString;
    tpudpvdv: z.ZodString;
    ctlfmxip: z.ZodString;
}, Record<never, unknown>>;
export declare const qyiytmtkusfvioifo: z.ZodInterface<{
    wigxpywl: z.ZodString;
    uqicpbze: z.ZodString;
    cogtgrpe: z.ZodString;
    wcxhgysh: z.ZodString;
    mhlcllgv: z.ZodString;
    uwlqsiog: z.ZodString;
    oxcaebde: z.ZodString;
    ertfytay: z.ZodString;
    nyvpeopf: z.ZodString;
    cnphmfsv: z.ZodString;
}, Record<never, unknown>>;
export declare const ocofgkfhcpfniarqj: z.ZodInterface<{
    zmipvftm: z.ZodString;
    kcgtqjhw: z.ZodString;
    gongywoe: z.ZodString;
    ylhouelm: z.ZodString;
    fkhjitsy: z.ZodString;
    cytocwdh: z.ZodString;
    myuisnhp: z.ZodString;
    dfaifwxl: z.ZodString;
    fnxymcfu: z.ZodString;
    rhfqxnot: z.ZodString;
}, Record<never, unknown>>;
export declare const qkvrqoqzemwgdwbxf: z.ZodInterface<{
    irmjzfzu: z.ZodString;
    xzrtnsas: z.ZodString;
    yoymakod: z.ZodString;
    knndxghq: z.ZodString;
    idxcmvau: z.ZodString;
    kekcxqcl: z.ZodString;
    drqroqox: z.ZodString;
    siufyail: z.ZodString;
    whvcjawa: z.ZodString;
    ycnpctrg: z.ZodString;
}, Record<never, unknown>>;
export declare const qancrhzsbzoxauwya: z.ZodInterface<{
    qnhnnhtk: z.ZodString;
    nzmhwnfp: z.ZodString;
    dqrwdrck: z.ZodString;
    eakhdzfy: z.ZodString;
    mckgbxam: z.ZodString;
    jfypdfiq: z.ZodString;
    gckdpxgy: z.ZodString;
    oloecbko: z.ZodString;
    ufjxiequ: z.ZodString;
    ispwymij: z.ZodString;
}, Record<never, unknown>>;
export declare const obdhzgrnettbjqdzn: z.ZodInterface<{
    mhjpcdfi: z.ZodString;
    diqpwqle: z.ZodString;
    tpijhvxy: z.ZodString;
    fdjrklqu: z.ZodString;
    csdtdgqa: z.ZodString;
    fizzewjw: z.ZodString;
    yecforww: z.ZodString;
    oyogbzsv: z.ZodString;
    ospvpdaq: z.ZodString;
    pmydnxno: z.ZodString;
}, Record<never, unknown>>;
export declare const ydgcoasgbqucaxzcj: z.ZodInterface<{
    xxoolpxr: z.ZodString;
    nbbbbjfw: z.ZodString;
    hchhyocg: z.ZodString;
    qjrxjdyb: z.ZodString;
    npwvvhmi: z.ZodString;
    kjuyhxay: z.ZodString;
    vrseuxdp: z.ZodString;
    modnzsca: z.ZodString;
    smueltid: z.ZodString;
    lbwezdmp: z.ZodString;
}, Record<never, unknown>>;
export declare const jvugfsxecsspltdel: z.ZodInterface<{
    wcvdmcsy: z.ZodString;
    aopcswfx: z.ZodString;
    peorluwk: z.ZodString;
    dpmyaurm: z.ZodString;
    blhfylbe: z.ZodString;
    oalribie: z.ZodString;
    lgtzkqrm: z.ZodString;
    yudgnsfk: z.ZodString;
    vmsduhyq: z.ZodString;
    hqqiyuwn: z.ZodString;
}, Record<never, unknown>>;
export declare const umuyaxhtlyysebvzh: z.ZodInterface<{
    qojxqusy: z.ZodString;
    sexyiqos: z.ZodString;
    bkduqjxw: z.ZodString;
    upguxahb: z.ZodString;
    yovosnmv: z.ZodString;
    vxzvljng: z.ZodString;
    gkhrjosk: z.ZodString;
    cxqsgofe: z.ZodString;
    arquiooa: z.ZodString;
    nmivacwr: z.ZodString;
}, Record<never, unknown>>;
export declare const lwfwrlfipymdsjrsj: z.ZodInterface<{
    ozxshorn: z.ZodString;
    wiqgorpn: z.ZodString;
    qrkfxzll: z.ZodString;
    uuonjhcj: z.ZodString;
    mexddgwt: z.ZodString;
    treqosvs: z.ZodString;
    fajpvuzp: z.ZodString;
    edbpcpos: z.ZodString;
    brrpzwdj: z.ZodString;
    zhgjaxek: z.ZodString;
}, Record<never, unknown>>;
export declare const xbgaxrnaffvalkrjg: z.ZodInterface<{
    lbvrmimr: z.ZodString;
    ubshuymy: z.ZodString;
    ducpyhto: z.ZodString;
    yhmkkwjc: z.ZodString;
    axzumfnx: z.ZodString;
    jckmdlvo: z.ZodString;
    edhxjlen: z.ZodString;
    dqnhrocg: z.ZodString;
    yckoildm: z.ZodString;
    nbdjhxrn: z.ZodString;
}, Record<never, unknown>>;
export declare const orkfybpjocwbqcrlf: z.ZodInterface<{
    xrgbtafe: z.ZodString;
    hgqioqdt: z.ZodString;
    jibjvlqi: z.ZodString;
    xwamgxsu: z.ZodString;
    jbzgfmtt: z.ZodString;
    bmwxfdcm: z.ZodString;
    jgywvqgc: z.ZodString;
    hujtuget: z.ZodString;
    rocgrbff: z.ZodString;
    wiarkwll: z.ZodString;
}, Record<never, unknown>>;
export declare const tobxjxicsvqnyaefk: z.ZodInterface<{
    csqutwgq: z.ZodString;
    zrhnepxf: z.ZodString;
    uroemccw: z.ZodString;
    gxfwpaoy: z.ZodString;
    brabtwjq: z.ZodString;
    dycfbgpm: z.ZodString;
    ygogymep: z.ZodString;
    qrsvuugv: z.ZodString;
    exwxvvhi: z.ZodString;
    dyoaxivw: z.ZodString;
}, Record<never, unknown>>;
export declare const hnaalnsrzvpniznju: z.ZodInterface<{
    rkdrlcei: z.ZodString;
    dszncepp: z.ZodString;
    rykaumte: z.ZodString;
    cwpiikue: z.ZodString;
    npqdarfg: z.ZodString;
    iloeqknn: z.ZodString;
    klwbdhim: z.ZodString;
    nmhbfbhy: z.ZodString;
    jpeqnubn: z.ZodString;
    euedrkbf: z.ZodString;
}, Record<never, unknown>>;
export declare const yvessdaoucrcxthaj: z.ZodInterface<{
    nlvdkzpo: z.ZodString;
    zflzuaim: z.ZodString;
    pyerkrwp: z.ZodString;
    xytkbkqe: z.ZodString;
    ntkblzsn: z.ZodString;
    ynvchnce: z.ZodString;
    jufudzju: z.ZodString;
    hvijggzc: z.ZodString;
    zvofvkya: z.ZodString;
    vtparopb: z.ZodString;
}, Record<never, unknown>>;
export declare const tjsqvgcuvomilwmqz: z.ZodInterface<{
    ijwqisvn: z.ZodString;
    cvbuaeey: z.ZodString;
    lgulosqg: z.ZodString;
    hdxsbhsb: z.ZodString;
    tiwdliwt: z.ZodString;
    bnjqsesi: z.ZodString;
    poqbgnqo: z.ZodString;
    llpfqpqj: z.ZodString;
    hfrpdzyo: z.ZodString;
    qykxbvrf: z.ZodString;
}, Record<never, unknown>>;
export declare const fgfhuimghjcfksawq: z.ZodInterface<{
    gyqmgdtn: z.ZodString;
    upptzqee: z.ZodString;
    wzlyhkyw: z.ZodString;
    exioygcc: z.ZodString;
    xsxjywhs: z.ZodString;
    gbtzwttj: z.ZodString;
    ahpoylbc: z.ZodString;
    jkunvtip: z.ZodString;
    ykpjhjge: z.ZodString;
    kqnbnbbf: z.ZodString;
}, Record<never, unknown>>;
export declare const bjpwznngparigqmie: z.ZodInterface<{
    eokvngvp: z.ZodString;
    bwwpcmbw: z.ZodString;
    yjdnfgqm: z.ZodString;
    lyxzeqvj: z.ZodString;
    owgatdav: z.ZodString;
    ogghhdaw: z.ZodString;
    lmootydf: z.ZodString;
    rabdhmtg: z.ZodString;
    zssbgahf: z.ZodString;
    zmhasbla: z.ZodString;
}, Record<never, unknown>>;
export declare const fntochxvvhamevzoi: z.ZodInterface<{
    qvpfenuw: z.ZodString;
    fqcabshj: z.ZodString;
    khhcnpql: z.ZodString;
    fmqicyml: z.ZodString;
    fsqaelgq: z.ZodString;
    kdzqnpny: z.ZodString;
    jhajsiej: z.ZodString;
    jlvsrikf: z.ZodString;
    mvioamqc: z.ZodString;
    ykmciwlf: z.ZodString;
}, Record<never, unknown>>;
export declare const chvcewenpjsstiukq: z.ZodInterface<{
    ckjsqfla: z.ZodString;
    xfsllphj: z.ZodString;
    nailqfei: z.ZodString;
    hqfowgeu: z.ZodString;
    gwozmole: z.ZodString;
    gnaulhdx: z.ZodString;
    hszxkkjf: z.ZodString;
    mcrmwgns: z.ZodString;
    etwpmhym: z.ZodString;
    vnkjgnut: z.ZodString;
}, Record<never, unknown>>;
export declare const vntlbloiklplxferj: z.ZodInterface<{
    eacxwmxa: z.ZodString;
    nehmsjou: z.ZodString;
    tqyrfhjs: z.ZodString;
    mqjgpkqr: z.ZodString;
    csbgqnlr: z.ZodString;
    tqdhgehc: z.ZodString;
    kicdlszv: z.ZodString;
    gbgyaesm: z.ZodString;
    fohyblpv: z.ZodString;
    jefcqchd: z.ZodString;
}, Record<never, unknown>>;
export declare const hxfabzjxeihmqpeiy: z.ZodInterface<{
    ptxejuia: z.ZodString;
    oswsmvbj: z.ZodString;
    trdosejf: z.ZodString;
    frdsnxca: z.ZodString;
    yrbgliuz: z.ZodString;
    drnydyqs: z.ZodString;
    xoquxtyk: z.ZodString;
    lidhtixe: z.ZodString;
    lfpmosam: z.ZodString;
    ugblqezv: z.ZodString;
}, Record<never, unknown>>;
export declare const chbfihkxrhabtoagw: z.ZodInterface<{
    nzpjlwop: z.ZodString;
    jotwjlrp: z.ZodString;
    qoqhkxcp: z.ZodString;
    qmtwmoub: z.ZodString;
    drlngpbn: z.ZodString;
    loxxwlzu: z.ZodString;
    tebyqdma: z.ZodString;
    vlipwihm: z.ZodString;
    tygrsnep: z.ZodString;
    uyohnefo: z.ZodString;
}, Record<never, unknown>>;
export declare const ohczkopfbrohacqwk: z.ZodInterface<{
    owkmzsjb: z.ZodString;
    smwhagrq: z.ZodString;
    tsmcomvt: z.ZodString;
    olymuctp: z.ZodString;
    ephzuolu: z.ZodString;
    rvwxgxbk: z.ZodString;
    pnmfogdg: z.ZodString;
    hxhhhmhv: z.ZodString;
    ixkzcurm: z.ZodString;
    vnchcnpu: z.ZodString;
}, Record<never, unknown>>;
export declare const nuxgxjajfledtewac: z.ZodInterface<{
    aobfibwb: z.ZodString;
    vhabwgqn: z.ZodString;
    focjqcbz: z.ZodString;
    yfoauydd: z.ZodString;
    qtdfanct: z.ZodString;
    avqnffxl: z.ZodString;
    etdxqycd: z.ZodString;
    zebztenu: z.ZodString;
    llupqsft: z.ZodString;
    ydtwsxhc: z.ZodString;
}, Record<never, unknown>>;
export declare const uwhftkxtbkmwoicht: z.ZodInterface<{
    iecqjlaw: z.ZodString;
    ezepibyx: z.ZodString;
    rscofmhz: z.ZodString;
    akbrwdbj: z.ZodString;
    mnexkqug: z.ZodString;
    ejorqgve: z.ZodString;
    urzbfpdp: z.ZodString;
    ffcposfn: z.ZodString;
    tekbfzco: z.ZodString;
    iekmvbgy: z.ZodString;
}, Record<never, unknown>>;
export declare const qkzxxurdalkcnjlsl: z.ZodInterface<{
    hcguyivn: z.ZodString;
    llnxhjqc: z.ZodString;
    kgwzsdre: z.ZodString;
    bbckpjuz: z.ZodString;
    uubjfpox: z.ZodString;
    pcikycjg: z.ZodString;
    ilhxnzyi: z.ZodString;
    ksohqhij: z.ZodString;
    gxwftaxc: z.ZodString;
    edlwluhn: z.ZodString;
}, Record<never, unknown>>;
export declare const rnucgxcmdyckmljgs: z.ZodInterface<{
    bricbcok: z.ZodString;
    kcpbmpeg: z.ZodString;
    qwyvbeom: z.ZodString;
    haekuqup: z.ZodString;
    xwbnuzjl: z.ZodString;
    mruruuxr: z.ZodString;
    cryvyvci: z.ZodString;
    kyswfrlq: z.ZodString;
    uokhsqeg: z.ZodString;
    saxtzncv: z.ZodString;
}, Record<never, unknown>>;
export declare const iofnfegssozfgcmno: z.ZodInterface<{
    dglarlqn: z.ZodString;
    jbjewxqj: z.ZodString;
    bprnyqtt: z.ZodString;
    yjzoutop: z.ZodString;
    xlqagiwg: z.ZodString;
    szamjudl: z.ZodString;
    gbtdbuca: z.ZodString;
    kygfbitt: z.ZodString;
    xpbucuyw: z.ZodString;
    etkebwjs: z.ZodString;
}, Record<never, unknown>>;
export declare const zduioimueaujwtpah: z.ZodInterface<{
    kdvtxgmi: z.ZodString;
    eatnstnv: z.ZodString;
    aaksittb: z.ZodString;
    ucxwhjxg: z.ZodString;
    cmhureqg: z.ZodString;
    cssyybfr: z.ZodString;
    sfuijwli: z.ZodString;
    hvpkqwtr: z.ZodString;
    ccrhnnie: z.ZodString;
    iqpomwgq: z.ZodString;
}, Record<never, unknown>>;
export declare const knmpjwvsljgwmsyzf: z.ZodInterface<{
    skvddcqk: z.ZodString;
    gaqsbvbc: z.ZodString;
    pqrosrpc: z.ZodString;
    jmwwlvdb: z.ZodString;
    jvngvbni: z.ZodString;
    aeyvibel: z.ZodString;
    nngueyuz: z.ZodString;
    nultldtm: z.ZodString;
    tipqsmhr: z.ZodString;
    zftuarvp: z.ZodString;
}, Record<never, unknown>>;
export declare const nlkbyhlpvklqgvtcf: z.ZodInterface<{
    tjzuqsxt: z.ZodString;
    hvsgsxlp: z.ZodString;
    lmurxily: z.ZodString;
    xdsithhp: z.ZodString;
    tetteqln: z.ZodString;
    kvyrgibr: z.ZodString;
    jyulfkvu: z.ZodString;
    efzowbwr: z.ZodString;
    otimpswy: z.ZodString;
    nrqkcxag: z.ZodString;
}, Record<never, unknown>>;
export declare const mxqvrblmatmvynkyw: z.ZodInterface<{
    gbirdzik: z.ZodString;
    hazwufzu: z.ZodString;
    szohmpcq: z.ZodString;
    pajflfsw: z.ZodString;
    hwqskvnt: z.ZodString;
    dciwwevb: z.ZodString;
    yhwxdfrm: z.ZodString;
    fqrsigut: z.ZodString;
    vopcjzfq: z.ZodString;
    biivbsdg: z.ZodString;
}, Record<never, unknown>>;
export declare const kllsvcwtytsghaecx: z.ZodInterface<{
    wlnlcnpm: z.ZodString;
    plkatapq: z.ZodString;
    nsvawaju: z.ZodString;
    xbzyxltc: z.ZodString;
    qazxvawy: z.ZodString;
    iohnqcdt: z.ZodString;
    tagdjuue: z.ZodString;
    qeoazgzr: z.ZodString;
    mcgpjsay: z.ZodString;
    vvlajajv: z.ZodString;
}, Record<never, unknown>>;
export declare const gpgpvvfscfmjffrdu: z.ZodInterface<{
    ttbwlduv: z.ZodString;
    zpsrxzzm: z.ZodString;
    whbqjaiu: z.ZodString;
    ypmqflmo: z.ZodString;
    tpcatvmc: z.ZodString;
    yzqkrykb: z.ZodString;
    pcfmshsy: z.ZodString;
    veoynikl: z.ZodString;
    bssxtigh: z.ZodString;
    esmbrvmr: z.ZodString;
}, Record<never, unknown>>;
export declare const weksemozzbkagolny: z.ZodInterface<{
    aylwvmkc: z.ZodString;
    segmjnue: z.ZodString;
    hadornko: z.ZodString;
    oxiredum: z.ZodString;
    meyvaxte: z.ZodString;
    keeuiptc: z.ZodString;
    lpelrshy: z.ZodString;
    ymnvrugm: z.ZodString;
    zxgostqd: z.ZodString;
    osabcsli: z.ZodString;
}, Record<never, unknown>>;
export declare const ligvbhjgkxyoapbat: z.ZodInterface<{
    koehxvtn: z.ZodString;
    udepwxae: z.ZodString;
    lxcvdjtk: z.ZodString;
    jaszbuiy: z.ZodString;
    wbfmhqmx: z.ZodString;
    kvfqvrgy: z.ZodString;
    ifsgjfnq: z.ZodString;
    qdpzoscn: z.ZodString;
    dvcrkqeu: z.ZodString;
    vrpdmdia: z.ZodString;
}, Record<never, unknown>>;
export declare const cxgsgmfvurvgdpbux: z.ZodInterface<{
    nqeivtvc: z.ZodString;
    wompnnak: z.ZodString;
    qdfxozot: z.ZodString;
    tyxkiakb: z.ZodString;
    ksfkdljw: z.ZodString;
    advrfsyw: z.ZodString;
    bwwsnvan: z.ZodString;
    jxsugmie: z.ZodString;
    difydylg: z.ZodString;
    xtkoeuyd: z.ZodString;
}, Record<never, unknown>>;
export declare const ozmnjelyyjhengnsy: z.ZodInterface<{
    xwetkywf: z.ZodString;
    wsuiydkg: z.ZodString;
    xykxfozk: z.ZodString;
    icxsxbyd: z.ZodString;
    bkecrrwx: z.ZodString;
    pvjrbjxn: z.ZodString;
    tqtbjrmp: z.ZodString;
    mmmjlict: z.ZodString;
    kprdbsyn: z.ZodString;
    otmmdiwn: z.ZodString;
}, Record<never, unknown>>;
export declare const gujegzrvgsltxsbyd: z.ZodInterface<{
    ivyrobiz: z.ZodString;
    ismaehhf: z.ZodString;
    wgrhavop: z.ZodString;
    ovhkxljk: z.ZodString;
    axpvbjkh: z.ZodString;
    dajzjsfq: z.ZodString;
    ruqptfks: z.ZodString;
    wkvtczzj: z.ZodString;
    lkhonvqm: z.ZodString;
    xbuijqtd: z.ZodString;
}, Record<never, unknown>>;
export declare const uvagygdozkmskrrbl: z.ZodInterface<{
    zwvuawig: z.ZodString;
    ibempeew: z.ZodString;
    uziyfhdq: z.ZodString;
    ddzecvzm: z.ZodString;
    flhmybuo: z.ZodString;
    trfklxkf: z.ZodString;
    wvelvpur: z.ZodString;
    tvdjckcp: z.ZodString;
    tpauehxo: z.ZodString;
    euidpgti: z.ZodString;
}, Record<never, unknown>>;
