import * as z from "zod";
const schema = z.object({ name: z.string(), age: z.number().int() });
const bad = { name: 1, age: 2.5 };
const N = 100_000;
const gc = (globalThis as any).gc as () => void;
const keep: unknown[] = new Array(N);
for (let i = 0; i < N; i++) keep[i] = schema["~standard"].validate(bad);
gc(); gc();
const before = process.memoryUsage().heapUsed;
keep.length = 0;
gc(); gc();
console.log("failing ~standard result", ((before - process.memoryUsage().heapUsed) / N).toFixed(0), "bytes/result");
