name: test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main
      - v4

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]
       typescript: ["5.5", "latest"]
    name: Test with TypeScript ${{ matrix.typescript }} on (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        run: |
          volta install pnpm@11.6.0
      - name: Check versions
        run: |
          node --version
          pnpm --version
      - run: pnpm install
      - run: pnpm add typescript@${{ matrix.typescript }} -w
      - run: pnpm build
      - run: pnpm test
      - run: pnpm run --filter @zod/resolution test:all
      - run: pnpm run --filter @zod/integration test:all

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        run: |
          volta install pnpm@11.6.0
      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm lint:check

  check-circular:
    runs-on: ubuntu-latest
    name: Check for circular dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        run: |
          volta install pnpm@11.6.0
      - run: pnpm install
      - run: pnpm check:circular
